/**
 * Create-{{ENTITY_SINGULAR}} modal — generated by Base-App Setup Wizard.
 * Wraps EventForm wired to the {{TABLE_NAME}} table.
 */
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';

import { useTheme } from '../../src/context/ThemeProvider';
import { EventForm } from '../../src/components/time-index/EventForm';

export default function Add{{ENTITY_SINGULAR}}Modal(): React.JSX.Element {
  const { theme } = useTheme();
  const router = useRouter();
  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <EventForm
        tableName="{{TABLE_NAME}}"
        onSuccess={() => router.back()}
        onCancel={() => router.back()}
      />
    </View>
  );
}

const styles = StyleSheet.create({ screen: { flex: 1 } });
