# {{APP_NAME}} — Manual Setup Remaining

Generated: {{GENERATED_DATE}} · Setup Wizard handled file generation, theme, roles, enums, migrations.

## Required (must do before launch)

### 1. Configure Email (5 min)
Supabase Dashboard → Authentication → SMTP Settings
- Host: {{SMTP_HOST}}
- Port: {{SMTP_PORT}}
- User: {{SMTP_USER}}
- From: {{EMAIL_FROM}}

### 2. Create First Admin (2 min)
1. Supabase Dashboard → Authentication → Users → Invite User
2. After accepting invite: Table Editor → user_profiles → set role = 'admin'

### 3. Confirm App Icons (2 min)
Icons generated by the wizard live in `assets/pwa-icons/`.
Update `app.json` `expo.icon` to point to your 1024×1024 source icon if you want custom sizes.

## Optional

### 4. Deploy to {{DEPLOY_PLATFORM}}
1. Connect repo to {{DEPLOY_PLATFORM}}
2. Build command: `npm run build:web`
3. Publish directory: `dist`
4. Add all `.env` values to environment variables
{{DEPLOY_DOMAIN_LINE}}

### 5. Email Templates
Apply branded templates from `docs/EMAIL_BRANDING.md` to Supabase auth email templates.

### 6. Slack Automation
See `docs/CURSOR_AUTOMATION_PROMPT.md` if you want automated bug/feature triage.
