/**
 * entity-sql — fields[] → CREATE TABLE migration.
 *
 * Output mirrors the conventions from 001/003: uuid PK, created_at/updated_at,
 * created_by → auth.users, RLS policies (authenticated read, manager+admin write),
 * full-text search index on the searchable fields.
 */

const TYPE_MAP = {
  text: 'TEXT',
  number: 'NUMERIC',
  date: 'DATE',
  time: 'TIME',
  datetime: 'TIMESTAMPTZ',
  boolean: 'BOOLEAN',
  enum: 'TEXT',
  tags: 'TEXT[]',
  image: 'TEXT',
  url: 'TEXT',
};

function snake(s) {
  return String(s || '')
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

function buildEntityMigration({ entitySingular, entityPlural, fields, searchableFields }) {
  const tableName = snake(entityPlural || `${entitySingular}s`);
  const userFields = (fields || []).filter(f => f.type !== 'card_break');

  const columnDefs = userFields.map(f => {
    const col = snake(f.name);
    const sqlType = TYPE_MAP[f.type] || 'TEXT';
    const nullable = f.required ? 'NOT NULL' : '';
    return `  ${col} ${sqlType}${nullable ? ' ' + nullable : ''}`.trimEnd();
  });

  const allColumns = [
    '  id UUID PRIMARY KEY DEFAULT gen_random_uuid()',
    ...columnDefs,
    '  created_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    '  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
    '  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL',
  ].join(',\n');

  const ftsCols = (searchableFields || [])
    .map(snake)
    .filter(c => userFields.some(f => snake(f.name) === c));
  const ftsIndex = ftsCols.length > 0
    ? `\nCREATE INDEX ${tableName}_fts_idx ON public.${tableName}\n  USING gin (to_tsvector('english',\n    ${ftsCols.map(c => `coalesce(${c}::text, '')`).join(" || ' ' || ")}\n  ));\n`
    : '';

  return `-- Migration: ${tableName}
-- Generated by Base-App Setup Wizard

CREATE TABLE IF NOT EXISTS public.${tableName} (
${allColumns}
);

ALTER TABLE public.${tableName} ENABLE ROW LEVEL SECURITY;

-- RLS: authenticated users can read
CREATE POLICY "${tableName}_select_authenticated" ON public.${tableName}
  FOR SELECT TO authenticated USING (true);

-- RLS: manager + admin can insert/update/delete
CREATE POLICY "${tableName}_write_manager" ON public.${tableName}
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid() AND up.role IN ('manager', 'admin') AND up.active = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid() AND up.role IN ('manager', 'admin') AND up.active = true
    )
  );

-- updated_at trigger
CREATE TRIGGER ${tableName}_set_updated_at
  BEFORE UPDATE ON public.${tableName}
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
${ftsIndex}`;
}

module.exports = { buildEntityMigration, snake };
