/**
 * env — write project .env from formData. Lifted from main.js (unchanged behavior).
 */
const fs = require('fs');
const path = require('path');

function buildEnv(d) {
  const supabase = d.supabase || {};
  const emailProvider = d.emailProvider || {};
  const identity = d.identity || {};
  const isResend = (emailProvider.type || 'resend') === 'resend';
  const tabs = d.tabs || {};
  const isLocation = (tabs.indexType || 'custom') === 'location';
  const isSensitive = (d.dataModel || {}).dataSensitive === true;

  return `# ==============================================================================
# ${identity.name || 'base-app'} — Environment Variables
# Generated by Base-App Setup Wizard
# ==============================================================================

# ── Supabase ───────────────────────────────────────────────────────────────────
EXPO_PUBLIC_SUPABASE_URL=https://${supabase.projectId || 'YOUR_PROJECT_ID'}.supabase.co
EXPO_PUBLIC_SUPABASE_ANON_KEY=${supabase.anonKey || ''}
SUPABASE_SERVICE_ROLE_KEY=${supabase.serviceRoleKey || ''}
SUPABASE_PROJECT_ID=${supabase.projectId || ''}
# DB password is required by the wizard for migration apply via pg pooler.
SUPABASE_DB_PASSWORD=${supabase.dbPassword || ''}${isLocation ? `

# ── Mapbox (location-indexed apps only) ───────────────────────────────────────
EXPO_PUBLIC_MAPBOX_TOKEN=${tabs.mapboxPublicToken || 'YOUR_MAPBOX_PUBLIC_TOKEN'}
MAPBOX_SECRET_TOKEN=${tabs.mapboxSecretToken || 'YOUR_MAPBOX_SECRET_TOKEN'}` : ''}

# ── Auth Email — Supabase SMTP ─────────────────────────────────────────────────
SMTP_HOST=${emailProvider.smtpHost || 'smtp.resend.com'}
SMTP_PORT=${emailProvider.smtpPort || '587'}
SMTP_USER=${emailProvider.smtpUser || 'resend'}
SMTP_PASS=${emailProvider.smtpPass || emailProvider.resendKey || ''}
SMTP_FROM_EMAIL=${(d.email || {}).fromAddress || 'noreply@yourdomain.com'}
SMTP_FROM_NAME=${(d.email || {}).senderName || identity.name || 'App Name'}

# ── Custom Transactional Email ─────────────────────────────────────────────────
EMAIL_PROVIDER=${isResend ? 'resend' : 'smtp'}
RESEND_API_KEY=${emailProvider.resendKey || ''}

# ── Slack + Cursor Automation ──────────────────────────────────────────────────
SLACK_BOT_TOKEN=${(d.deployment || {}).slackBotToken || ''}
SLACK_BUG_REPORTS_CHANNEL_ID=${(d.deployment || {}).slackBugChannel || ''}
SLACK_FEATURE_REQUESTS_CHANNEL_ID=${(d.deployment || {}).slackFeatureChannel || ''}
CURSOR_API_KEY=

# ── App ────────────────────────────────────────────────────────────────────────
APP_URL=${(d.identity || {}).url || 'https://your-app.netlify.app'}
${isSensitive ? '# Sensitive mode: AI uses database/schema.md instead of live queries.\n' : ''}`;
}

function applyEnv(targetDir, formData) {
  fs.writeFileSync(path.join(targetDir, '.env'), buildEnv(formData), 'utf8');
}

module.exports = { applyEnv, buildEnv };
