/**
 * mapbox-config — write src/constants/mapConfig.ts and patch app.json plugins for
 * @rnmapbox/maps when the app is location-indexed.
 */
const fs = require('fs');
const path = require('path');

function applyMapbox(targetDir, formData) {
  const tabs = formData.tabs || {};
  if ((tabs.indexType || 'custom') !== 'location') return;

  const mapboxToken = tabs.mapboxPublicToken || 'YOUR_MAPBOX_PUBLIC_TOKEN';
  const secretToken = tabs.mapboxSecretToken || 'YOUR_MAPBOX_SECRET_TOKEN';

  // 1. mapConfig.ts
  const mapConfigPath = path.join(targetDir, 'src', 'constants', 'mapConfig.ts');
  if (fs.existsSync(mapConfigPath)) {
    fs.writeFileSync(mapConfigPath, `/**
 * Mapbox configuration — generated by Base-App Setup Wizard.
 * Get tokens at https://account.mapbox.com/access-tokens/
 */
export const MAPBOX_ACCESS_TOKEN = '${mapboxToken}';
`, 'utf8');
  }

  // 2. app.json plugin entry for @rnmapbox/maps
  const appJson = path.join(targetDir, 'app.json');
  if (!fs.existsSync(appJson)) return;
  const obj = JSON.parse(fs.readFileSync(appJson, 'utf8'));
  obj.expo = obj.expo || {};
  obj.expo.plugins = obj.expo.plugins || [];

  const existing = obj.expo.plugins.findIndex(p =>
    Array.isArray(p) ? p[0] === '@rnmapbox/maps' : p === '@rnmapbox/maps');
  const pluginEntry = ['@rnmapbox/maps', { RNMapboxMapsDownloadToken: secretToken }];
  if (existing >= 0) obj.expo.plugins[existing] = pluginEntry;
  else obj.expo.plugins.push(pluginEntry);

  fs.writeFileSync(appJson, JSON.stringify(obj, null, 2) + '\n', 'utf8');
}

module.exports = { applyMapbox };
