/**
 * Setup wizard configuration — tracks which setup steps were completed by the wizard.
 *
 * This file is overwritten by tools/setup-wizard when a developer runs the desktop
 * setup wizard. Default values (WIZARD_RAN = false) mean the wizard has not been run,
 * so all checklist items remain in their normal auto-detect / manual state.
 *
 * Do not edit this file manually — it is managed by the setup wizard.
 */

export const WIZARD_RAN = false;

export const WIZARD_COMPLETED_AT: string | null = null;

/**
 * IDs of setup checklist items that the wizard completed automatically.
 * These items are pre-marked as done in the Setup Checklist tab.
 *
 * When wizard runs: ['prd_filled', 'env_configured']
 */
export const WIZARD_COMPLETED_ITEMS: readonly string[] = [];
