/**
 * {{TAB_TITLE}} tab — placeholder generated by Base-App Setup Wizard.
 * Custom tab requested by user. Wire it to your data and UI.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function {{COMPONENT_NAME}}Screen(): React.JSX.Element {
  const { theme } = useTheme();
  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.{{PAGE_ID_KEY}} as any} />
      <Text style={[styles.title, { color: theme.colors.text }]}>{{TAB_TITLE}}</Text>
      <Text style={[styles.hint, { color: theme.colors.textMuted }]}>
        TODO: implement this custom tab — see SETUP_TODO.md.
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 24, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 20, fontWeight: '700', marginBottom: 8 },
  hint: { fontSize: 13, textAlign: 'center', maxWidth: 320 },
});
