/**
 * List tab — sortable list of {{ENTITY_PLURAL}}.
 * Generated by Base-App Setup Wizard.
 */
import React, { useEffect, useState } from 'react';
import { View, Text, FlatList, StyleSheet, ActivityIndicator } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { supabase } from '../../src/lib/supabase';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function ListScreen(): React.JSX.Element {
  const { theme } = useTheme();
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const { data } = await supabase.from('{{TABLE_NAME}}').select('*').order('created_at', { ascending: false }).limit(200);
      setRows(data || []);
      setLoading(false);
    })();
  }, []);

  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.LIST as any} />
      {loading ? <ActivityIndicator color={theme.colors.primary} /> : (
        <FlatList
          data={rows}
          keyExtractor={r => r.id}
          renderItem={({ item }) => (
            <View style={[styles.row, { borderBottomColor: theme.colors.border }]}>
              <Text style={[styles.title, { color: theme.colors.text }]}>{item.title || item.name || item.id}</Text>
            </View>
          )}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1 },
  row: { padding: 14, borderBottomWidth: StyleSheet.hairlineWidth },
  title: { fontSize: 15, fontWeight: '600' },
});
