/**
 * Month tab — generated by Base-App Setup Wizard.
 */
import React from 'react';
import { View, StyleSheet } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { MonthView } from '../../src/components/time-index/MonthView';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function MonthScreen(): React.JSX.Element {
  const { theme } = useTheme();
  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.MONTH as any} />
      <MonthView tableName="{{TABLE_NAME}}" />
    </View>
  );
}

const styles = StyleSheet.create({ screen: { flex: 1 } });
