/**
 * Reports tab — placeholder. Generated by Base-App Setup Wizard.
 * Wire your aggregations + chart library here.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function ReportsScreen(): React.JSX.Element {
  const { theme } = useTheme();
  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.REPORTS as any} />
      <Text style={[styles.body, { color: theme.colors.text }]}>
        Reports for {{ENTITY_PLURAL}} go here.
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 16 },
  body: { fontSize: 14 },
});
