/**
 * Search tab — full-text search over {{ENTITY_PLURAL}}.
 * Generated by Base-App Setup Wizard.
 */
import React, { useState } from 'react';
import { View, Text, TextInput, FlatList, StyleSheet, ActivityIndicator } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { supabase } from '../../src/lib/supabase';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function SearchScreen(): React.JSX.Element {
  const { theme } = useTheme();
  const [q, setQ] = useState('');
  const [results, setResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const run = async (term: string) => {
    if (!term.trim()) { setResults([]); return; }
    setLoading(true);
    const { data } = await supabase
      .from('{{TABLE_NAME}}')
      .select('*')
      .textSearch('fts', term, { type: 'websearch' })
      .limit(50);
    setResults(data || []);
    setLoading(false);
  };

  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.SEARCH as any} />
      <TextInput
        style={[styles.input, { borderColor: theme.colors.border, color: theme.colors.text }]}
        placeholder="Search {{ENTITY_PLURAL}}..."
        placeholderTextColor={theme.colors.textMuted}
        value={q}
        onChangeText={t => { setQ(t); run(t); }}
      />
      {loading ? <ActivityIndicator color={theme.colors.primary} /> : (
        <FlatList
          data={results}
          keyExtractor={r => r.id}
          renderItem={({ item }) => (
            <Text style={[styles.row, { color: theme.colors.text, borderBottomColor: theme.colors.border }]}>
              {item.title || item.name || item.id}
            </Text>
          )}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 16 },
  input: { borderWidth: 1, borderRadius: 8, padding: 10, marginBottom: 12 },
  row: { padding: 12, borderBottomWidth: StyleSheet.hairlineWidth },
});
