/**
 * {{TAB_TITLE}} tab — generated by Base-App Setup Wizard.
 * Wires DayView to the {{ENTITY_PLURAL}} table. Customize as needed.
 */
import React from 'react';
import { View, StyleSheet } from 'react-native';

import { useTheme } from '../../src/context/ThemeProvider';
import { DayView } from '../../src/components/time-index/DayView';
import { PageIdDisplay } from '../../src/components/common';
import { PAGE_IDS } from '../../src/constants/version';

export default function {{TAB_TITLE}}Screen(): React.JSX.Element {
  const { theme } = useTheme();
  return (
    <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>
      <PageIdDisplay pageId={PAGE_IDS.{{TAB_SLUG}} as any} />
      <DayView tableName="{{TABLE_NAME}}" />
    </View>
  );
}

const styles = StyleSheet.create({ screen: { flex: 1 } });
